version: '3.7'
services:

  postgres:
    image: postgres:latest
    env_file: ./config/pg_database/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  cache:
    image: redis:latest
    volumes:
      - cache:/data
    # expose:
    #   - "6379"
    ports:
      - 6379:6379

  solution:
    volumes:
      - ./solution:/app
    env_file: ./config/solution/.env
    build:
      context: ./solution/
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - cache
    ports:
      - 8000:8000

  migrate:
    volumes:
      - ./solution:/app
    env_file: ./config/solution/.env
    build:
      context: ./solution/
      dockerfile: Dockerfile_migrate
    command: 
      - /bin/bash
      - -c
      - |
       alembic revision --autogenerate 
       alembic upgrade head
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/solution.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - solution

volumes:
  cache:
    driver: local

